### ISSUE TITLE
Include styles so it looks like the demo site.

### ISSUE THREAD

**Issue by jdelia** [copyblogger/genesis-simple-faq#32]
These styles seem to be missing from the plugin but are needed for it to look the way the StudioPress demo does. I was scratching my head after installing the plugin, wondering if I was missing a step. https://demo.studiopress.com/genesis-sample/sample/faqs/

https://cl.ly/1P263T3A3i30

Might be a good idea to include them? 

I've put them here and am using them on my Genesis Sample test site. So now the output matches. 
https://cl.ly/3I0H1k3G2g0T
https://gist.github.com/jdelia/82d9869941c0c1321ede1b6e62033f1c#file-genesis-simple-faq-styles-css

**Comment by bgardner** [comment]
The plugin out of the box doesn't have much CSS on purpose, because we didn't want to conflict with any theme. So it inherits the theme's <button> styles.

We were waiting for initial testing to be done before officially moving the styles into the Sample theme for release. It's in trunk, just not the latest stable version yet. (see https://github.com/copyblogger/genesis-sample/commit/d7db197438d6048d366d2664c2e08a2730818f32)

**Comment by jdelia** [comment]
Thanks, Brian. Makes sense. I was just expecting it to match the demo by default and hence that led me to think I did not do something correctly. I viewed the demo site and pulled the CSS from inspect element stylesheet and that worked just fine. Others might also think the same way, so perhaps just showing that code in the readme might be helpful??

**Comment by bgardner** [comment]
It's mentioned here: https://my.studiopress.com/documentation/genesis-simple-faqs/plugin-usage/change-the-appearance-of-the-genesis-simple-faqs/

**Comment by jdelia** [comment]
Well duh - my bad.
