### ISSUE TITLE
FAQ does not collapse New WP update

### ISSUE THREAD

**Issue by StudiopressUser** [copyblogger/genesis-simple-faq#40]
The FAQ accordion feature no longer works with recent WP update.  They do not collapse.

**Comment by nickcernis** [comment]
@StudiopressUser Thanks for the report, but I couldn't reproduce the issue so far. FAQ accordions are collapsable for me in WordPress 4.9.2 with Genesis Simple FAQ 0.9.1 and Genesis Sample:

![faq-test](https://user-images.githubusercontent.com/647669/35197423-5f6e151e-fedf-11e7-9527-fb6bf9e7ccff.gif)

Perhaps you could try:

- Disabling all plugins.
- Checking for errors in your browser's JavaScript console.
- Linking to a page where this issue is visible, and/or explaining the steps to reproduce it in more detail.

**Comment by StudiopressUser** [comment]
It seems it was a .js conflict.  A server reset fixed it.  Thanks for confirming it wasn't the plugin.
